export default [
  {
    id: '1',
    name: 'Kancelaria Website (2013)',
    github: '',
    live: 'http://www.notariusz-kania.com/',
    heroImage: 'Hero Image',
    technologies: [
      {
        photoshop: true,
        illustrator: true,
        selfdesigned: true,
        xd: false,
        rjs: false,
        rwd: true,
        sass: false,
        styledcomponent: true,
        html: true,
      },
    ],
  },
  {
    id: '2',
    name: 'Some Website',
    github: '',
    live: '',
    heroImage: 'Hero Image',
    technologies: [
      {
        photoshop: true,
        illustrator: true,
        selfdesigned: false,
        xd: false,
        rjs: true,
        rwd: true,
        sass: true,
        styledcomponent: false,
        html: false,
      },
    ],
  },
  {
    id: '3',
    name: 'PiwoManiak Website (2013)',
    github: '',
    live: 'http://www.piwomaniak.com/',
    heroImage: 'Hero Image',
    technologies: [
      {
        photoshop: true,
        illustrator: true,
        selfdesigned: true,
        xd: false,
        rjs: false,
        rwd: false,
        sass: false,
        styledcomponent: false,
        html: true,
      },
    ],
  },
  {
    id: '4',
    name: 'Weather App',
    github: 'https://github.com/jakub84/weather-app',
    live: 'https://jakub84.github.io/weather-app/',
    heroImage: 'Hero Image',
    technologies: [
      {
        photoshop: false,
        illustrator: true,
        selfdesigned: true,
        xd: true,
        rjs: true,
        rwd: true,
        sass: true,
        styledcomponent: false,
        html: false,
      },
    ],
  },
  {
    id: '5',
    name: 'Hangman Game',
    github: 'https://github.com/jakub84/game',
    live: 'https://jakub84.github.io/game/',
    heroImage: 'Hero Image',
    technologies: [
      {
        photoshop: false,
        illustrator: true,
        selfdesigned: true,
        xd: true,
        rjs: true,
        rwd: true,
        sass: true,
        styledcomponent: false,
        html: false,
      },
    ],
  },
];
